# Docker compose file with two services
# One building the image specified in the 
# build file docker/Dockerfile.pgp using
# context '.' named "gpg-terminal", launch
# script is bash.
# The other one is named "pgp-verify" and it
# uses build file docker/Dockerfile.veriy and 
# context './app'.

version: '3.7'

services:
  gpg-terminal:
    image: gpg-terminal
    build:
      context: .
      dockerfile: docker/Dockerfile.gpg
    command: bash
  gpg-verify:
    image: gpg-verify
    build:
      context: .
      dockerfile: docker/Dockerfile.verify
    network_mode: "host"


