version: '3.7'

services:
  gpg-terminal:
    image: gpg-terminal
    build:
      context: .
      dockerfile: docker/Dockerfile.gpg
    command: bash
  gpg-verify:
    image: gpg-verify
    build:
      context: .
      dockerfile: docker/Dockerfile.verify
    ports:
      - "8883:8883"


