# Dockerfile for ubuntu:latest that has gpg installed
# with the proof of human keyring
# Context: stand in the root of the repo
FROM ubuntu:latest

RUN apt-get update && apt-get install -y gnupg

WORKDIR /usr/app

COPY ./keys/keyring.asc /usr/app

RUN gpg --import keyring.asc

CMD ["/bin/bash"]
