name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install nettle-dev protobuf-compiler
      - name: Build
        run: cd app && cargo build --verbose
      - name: Run tests
        run: cd app && cargo test --verbose
